DESCRIPTION
inst/resources/init-rprofile.R
inst/resources/init.R

This fixes #183 by ensuring that the working directory is set to the project directory when sourcing the `packrat/init.R` file, and then restoring it after completing initialization.

ensure working directory set to project directory on restart

---

DESCRIPTION
NEWS.md
R/dependencies.R
inst/resources/init-rprofile.R
inst/resources/init.R
tests/testthat/resources/interactive-doc-example.Rmd
tests/testthat/test-shiny.R

This PR checks whether a project (implicitly) depends on Shiny. It does so by checking:
1. For a `shinyServer` call in `server.R`, or
2. A `shinyApp` call in `app.R`.
Note that `shiny` dependencies within R Markdown documents with `runtime: shiny` in the YAML header are already properly detected by us.
@jjallaire, can you merge if you think everything looks okay?

infer whether project implicitly depends on Shiny

---

R/install.R

print error message during package installation into stderr in case message is too long (#189)

---

DESCRIPTION
NEWS.md
R/cache.R
R/library-support.R
R/paths.R
R/restore.R
inst/resources/init-rprofile.R
inst/resources/init.R

This PR fixes a bug in packrat where help calls, e.g. `?stringr::str_c`, would fail if the project was using the packrat cache.
In essence, this PR changes the cache directory structure from:
<cachePath>/<pkgName>/<hash>
to
<cachePath>/<pkgName>/<hash>/<pkgName>
Because this PR changes the directory structure for packages within the cache, the cache directory is updated from `v1` to `v2` -- so all versions of packrat from here-on would use a new cache directory, to be safe.

set parent directory name for package to package name (#194)

---

DESCRIPTION
R/dependencies.R
inst/resources/init-rprofile.R
inst/resources/init.R

This PR ensures that we crawl through all library paths when attempting to resolve (recursive) package dependencies on the system.

use full set of .libPaths to resolve package dependencies

---

R/cache.R

Fixes the first and second parts of #202.
The GitHub SHA is never taken verbatim as the hash but included in the content we use to compute the hash for an installed package. This also lets us distinguish between CRAN and GitHub installed packages due to the presence of `GithubSHA1` (perhaps there are more attributes?).

Consider the GitHub SHA as just another hash input.

---

R/downloader.R
R/packrat-mode.R

Two changes here:
1) Update the `download` method to take advantage of the new secure R 3.2 download methods ("wininet" and "libcurl") when available.
2) Add a new `secureDownloadMethod` function which sets the default R download method to a secure one (if possible) when one of the repositories in `getOption("repos")` uses https. This allows `available.packages` and `install.packages` to work correctly in the presence of https repository URLs.
@jcheng5 @trestletech @wch
Winston, I'll put in a similar PR into downloader soon (packrat includes a copy of the the downloader::download function so as not to take a dependency on any other packages).

use secure download method for interactions with CRAN when required

---

DESCRIPTION
R/restore.R

We have a couple of instances where we build packages during deployment and feed the progress out to the user as the packrat library restores.
Unfortunately, we (among others) buffer to newline, meaning we get no information about what's going on until the end of the "Installing" line. Currently, that means we can see when a package is done installing but we get no update until that point.
This PR breaks the line showing that the installation has begun from the one showing it has completed.

Add newline when installing package.

---

R/downloader.R
R/packrat-mode.R
R/utils.R
tests/testthat/test-cranlike-repositories.R
tests/testthat/test-downloader.R

NOTE: This PR will need some pretty thoughtful review to ensure it's correct...
There are two overarching issues that this PR attempts to resolve:
1) When an external program (e.g. `wget`, `curl`) fails to download a file, the status code from running the program is logged as a warning when non-zero, but no error is emitted. This is in contrast to the behaviour of `method = "internal"`, which _does_ err in such a case.
2) With R (SVN revision < 69197), `libcurl` also does not respect HTTP error codes; even worse, it downloads the 404 page and returns a 0 (success) status code. This is only fixed in recent R SVN revisions.
For 1), we catch warnings from `download.file()` when using methods `curl` and `wget`, and err if a non-zero status code is returned.
For 2), we only enable `libcurl` on …

ensure downloader respects HTTP error codes

---

R/dependencies.R
R/snapshot.R

By default packrat itself is included as an implicit dependency by `snapshotImpl`, there are use cases (`rsconnect`) where this is not desirable. This PR adds a parameter to disable this dependency by passing `implicit.packrat.dependency = FALSE` to `snapshotImpl`

Add implicit.packrat.dependency parameter to snapshotImpl

---

DESCRIPTION
R/downloader.R
R/github.R
R/restore.R
R/utils.R
inst/resources/init-rprofile.R
inst/resources/init.R
tests/testthat/test-github.R

This PR modifies the packrat downloader to use `devtools::download()` when available.

use devtools downloader when available

---

DESCRIPTION
R/dependencies.R

Currently if a custom output format from another package is used in an Rmd it is not detected as a dependency, e.g. for
```yaml
output: mypackage::myformat
```
`mypackage` is not detected as a dependency.
This PR calls into the `rmarkdown::default_output_format` function to determine if there is a custom format implemented within a package and adds that package to the dependencies.
Note that there is already some processing of the yaml within Rmd files however this is all based regular expressions and determining the default format would involve both much more complex parsing (using the yaml package) as well as doing a bunch of other resolution (e.g. looking for an `_output.yml` file in the Rmd file's directory) so it's much better to call into the rmarkdown package for this.
Note that 3 …

detect Rmd dependencies based on custom output formats

---

R/library-support.R

In Windows, if the symlink fails (e.g. on a networked drive), an empty folder will be created. So by just checking if the folder exists, we aren't actually checking if the symlink was successful. We need to go inside the folder and see if the files actually exist like we expect them to.

Checking for failed symlinks

---

README.md

As a sidenote, I just had a first run with profvis, the use of package::function is actually very costly in terms of time, I am not sure this so such a good practice. In this case, in the documentation of a package, I think it is safe to assume the user can load the package.

update install instructions to CRAN

---

R/github.R
R/restore.R
tests/testthat/test-github.R

This PR modifies packrat to use GitHub API URLs when downloading packages, and tweaks some of the authentication code (to handle the case with no `GITHUB_PAT` set)

use GitHub tarball API when downloading packages

---

R/utils.R

I'm using packrat to distribute an R script in a shared environment where users only need read access to the script and packrat library. This works well, but when the `.gitignore` file is only user-writeable things break:
```
$ chmod 755 .gitignore
$ su testuser
$ ##run R script##
Error in file(file, ifelse(append, "a", "w")) :
cannot open the connection
Calls: source ... updateSettings -> updateGitIgnore -> updateIgnoreFile -> cat -> file
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
cannot open file '.gitignore': Permission denied
Execution halted
```
The content of the `.gitignore` file does not actually need to be updated:
```
$ cat .gitignore
packrat/lib*/
$ md5sum .gitignore
b8b019322d9d464c11f220816db44a76 .gitignore
$ chmod 766 .gitignore
$ su testuser
$ …
```

Don't write "ignore-file" unless the content actually changes

---

R/packrat.R

This allows successful, repeated `packrat::restore` when using a private repository.
Builds on #315 
The one thing I dislike about this approach is that we have a mixture of `repos` passed as a function argument and `repos` available via `getOption("repos")`. This inconsistency can be confusing when reading through the code. It would be nice to shift to one model or the other.

set the repos option during restore so it is available downstream

---

R/cache.R

When there are lots of newly installed packages and they need to be added to
the package cache, promoting these packages to the cache can take lots of time
(due to #325). Add some messaging for transparency into this process.
Related to #325 (but does not address it)

messaging about enrolling packages in the package cache.

---

R/env.R
R/packrat-mode.R
R/paths.R
R/utils.R
R/zzz.R

This PR should help ensure that R processes launched while within packrat mode inherit the current packrat state (project paths, and so on).

use environment variables to track packrat state

---

R/dependencies.R

This fixes an issue on Windows with UTF-8 encoded R Markdown documents. Previously, we'd fail when attempting to determine their dependencies because `rmarkdown::default_output_format` requires the correct encoding, and cannot infer UTF-8. 
Now, we try the native encoding first, but when we can't parse the output format with the native encoding, we try UTF-8. 
NB: this is meant to address the most common failure mode; for a fully robust solution we could for instance laboriously try every encoding in `iconvlist()`, perhaps sorted by likelihood, until we got one that worked.

Fall back to UTF-8 encoding on failure to determine format

---

R/dependencies.R
tests/testthat/resources/alternate-engines.Rmd
tests/testthat/resources/no-chunks.Rmd
tests/testthat/test-dependencies.R

This small change maintains compatibility with releases of knitr which do not have the very recent change https://github.com/yihui/knitr/commit/70986820cb5bec57b1d421ba8a74d5db8fcd410e. 
Prior to that change, knitr would emit non-R engine code verbatim into the tangled R file. This file would then become unparseable, which would in turn prevent Packrat from discovering dependencies in it. The fix here is elide the non-R code from the tangled R file prior to parsing it.

Strip code executed by alternate engines before parsing

---

R/cache.R
R/paths.R
R/restore-routines.R
R/restore.R
R/snapshot.R
tests/testthat/test-cache.R

This PR implements an alternative cache source for untrusted client packages. The goal here is to allow users to deploy applications bundling their own package sources, but ensure that these package sources live in a separate cache from the 'global' cache (to avoid malicious users poisoning the cache).
The main way this works:
- The 'untrusted' cache lives as a separate directory inside the global cache directory,
- Hashes are produced from the source tarballs uploaded by the user,
- Otherwise, the same cache machinery stays in play.
Users of the untrusted cache will need to explicitly set the `packrat.untrusted.packages` R option, to signal to Packrat which packages that are about to be restored truly are untrusted.
cc: @trestletech. Main TODO here -- add some unit tests + confirm the …

initial work on untrusted cache

---

R/bundle.R

If we try to change the working directory before checking the length of `dirName`, we don't get the right protection from problems working out the `dirName`. The call to `setwd` will fail with an argument of `character(0)`. We will get the following
```
Error in setwd(dirName) : character argument expected
```
rather than the error message "Couldn't infer top-level directory name..." as intended.

Change to dir after checking name length.

---

R/dependencies.R
tests/testthat/resources/evaluate-deps.Rmd
tests/testthat/test-rmarkdown.R

This allows us to extract dependencies from R Markdown files that contain parse errors in some of their chunks.

use an evaluate hook to discover rmd deps

---

R/snapshot.R

This PR fixes some issues noted by users where dependent packages did not have their associated `Requires:` field written out during `snapshot()`.
Fixes #391.

roll back non-recursive dependency search

---

DESCRIPTION
NEWS.md
R/aaa-globals.R
R/available-packages.R
R/dependencies.R
R/packrat.R
R/recursive-package-dependencies.R
R/restore.R
R/snapshot.R
R/status.R
R/utils.R
inst/resources/init-rprofile.R
inst/resources/init.R
tests/testthat/helper-bundle.R
tests/testthat/helper-packrat.R
tests/testthat/test-bundle.R

This PR should help resolve an issue spotted by @trestletech where attempts to restore a project on e.g. macOS when using a CRAN mirror that did not supply binary packages would fail.
The underlying issue here was that Packrat inadvertently attempted to use the binary repositories, rather than the source repositories, when attempting to ascertain if a package was available and current, or available in the CRAN archives.
This PR also performs in-memory caching of the output retrieved by `available.packages()`, just to speed up processing when `available.packages()` is called recursively.

differentiate between binary, source repos during restore

---

NEWS.md
R/packrat.R
R/snapshot.R
man/init.Rd
man/snapshot.Rd
man/snapshotImpl.Rd
tests/testthat/test-packrat.R

Hello,
This is to allow a packrat project to be initialised without searching the code for dependencies. It is useful to have more control of what package versions etc are installed when initialising packrat for a work in progress project.
I think this would close https://github.com/rstudio/packrat/issues/258.
To do this an `infer.dependencies` argument has been added to the `init` function (and also `snapshot` as this could be useful as well).
Tests all pass and an additional test has been added.
I've sanity checked by initialising a new project with the new argument and without it.
(Also, thanks for creating and maintaining packrat!)

Inference of dependencies optional on initialisation

---

R/options.R
man/packrat-options.Rd

Clarify version control configuration options in documentation, based on conversation in issue #332.

clarify vcs options in documentation

---

DESCRIPTION
R/downloader.R
R/restore.R

The `fileLoc` error was caused by a failed package download. We trapped for that failed download but only triggered a `warning` instead of `stop`. This change retries `download.packages` (modeled after `downloadWithRetries`) and stops if the retried download results in no `fileLoc` rows.
fixes #404

retry download.packages and stop if nothing is downloaded

---

R/paths.R
man/packrat-resources.Rd

The "lib-r" and "lib-ext" directories can be customized following
the same pattern as the "src" and "lib" directories. But this is
not mentioned anywhere in the documentation.
Adding it to the table that describes the other path customization
options, under the "packrat-resources" help page.

Adding docs for some undocumented options

---

R/paths.R
man/packrat-resources.Rd

I just noticed a typo in my previous patch, PR #421. The default path for libR is `packrat/lib-R`, not `packrat/lib-r`.

Correcting typo in packrat.lib-r.dir docs

---

R/dependencies.R
R/options.R
tests/testthat/projects/partlyignored/ignoreme/ignorethis.R
tests/testthat/projects/partlyignored/notignored.R
tests/testthat/test-packrat.R

This pull request adds a new option `ignore.directories`, that will tell packrat not to scan for dependencies in the R code in those directories.
My personal use-case for this, is that I have copies of some older reports in my project's git repository. They're useful for reference purposes, but I don't want their dependencies installed, and I don't want to see the warning about them being untracked every time I do `packrat::status()`.
When I was searching the Internet to see if there was an existing solution for this, I found that a second use-case is if a project has a very large amount of files in the `./data` directory, in which case it takes packrat a long time to scan them.

Tell packrat not to look for dependencies in certain directories

---

R/paths.R

Hit invalid `getwd()` under `packrat::opts$quiet.package.installation()` while troubleshooting `cloudml`:

Fix invalid getwd() while retrieving quiet.package.installation()

---

R/lockfile-metadata.R

Hey, 
This is related #425. @kevinushey I followed you advice and made one function to change different metadata. Just two for the moment `repos` and `r_version`. I think the others are not useful to modify. 
Can you take a look and tell me if the direction I took is ok ? 
I tried to write some tests but I don't manage to make them work. It seems like other test are not working either. 
I tried something like that
```r
projRoot <- cloneTestProject("healthy")
init(enter = FALSE, projRoot, options = list(local.repos = "packages"))
``` 
but `init` does not work as expected.
help appreciated for those tests. thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rstudio/packrat/429)

Set metadata in packrat lockfile

---

R/restore-routines.R

cloudml is blocked from using packrat restore since I'm hitting this bug in `restoreWithCopyFromCache()` where we test for a file instead of a dir.

restoreWithCopyFromCache to check for dir not file

---

R/lockfile.R
R/pkg.R
R/restore.R

resolves #442 and #447 by removing hard-coded `api.github.com` URL in download step.  Packages installed from private github repos are not located at api.github.com.  
Instead, this generates the url from the RemoteHost variable from the DESCRIPTION file, which should specify where the package was installed from.  The RemoteHost variable is also used to generate the protocol.  The protocol choice for users using `method='internal'`, has been removed, which could cause unwanted side-effects.
Rather than using `downloadWithRetries()`, which attempts to `inferAppropriateDownloadMethod`, and was leading to `method=libcurl`, which looks like it is not supported in `canUseLibCurlDownloadMethod`, we choose to use `githubDownload()`, since we know it is a github repo.
To work, the user must set …

Bugfix/snapshot private GitHub packages

---

R/lockfile.R
R/pkg.R
R/restore.R

I've added all remote_ variables to github download as these could be different from the values in the `gh_` fields

githubDownload uses remote variables

---

NEWS.md
R/install.R
R/migrate-library.R
R/snapshot.R
README.md
announce/packrat-0.3.0.md
inst/resources/mac_r_userlib.sh
internal/digestPkg.sh
internal/shinyPkg.sh
internal/testPkg.sh
tests/testthat/lockfiles/lockfile-multipleRepos.txt
tests/testthat/resources/interactive-doc-example.Rmd
tests/testthat/resources/knitr-minimal.Rnw
tests/testthat/test-lockfile.R
tests/testthat/test-shiny.R

Hey, thanks for this awesome library 👍 
This PR changes Packrat use HTTPS by default. It switches the default repo from `http://cran.rstudio.com/` to `https://cran.rstudio.com/`, as well as updates links in the doc that are also available over HTTPS.

Make Packrat secure by default

---

DESCRIPTION
NEWS.md
R/library-support.R
R/options.R
inst/resources/init-rprofile.R
inst/resources/init.R

This allows users to opt-in to using the system libraries as-is, in case the user explicitly wants to use user-installed packages that have found their way into the system library.

allow user to configure symlinking of system packages

---

R/available-updates.R
R/bitbucket.R
R/cache.R
R/downloader.R
R/lockfile.R
R/migrate-library.R
R/packrat.R
R/pkg.R
R/restore.R
R/snapshot.R
tests/testthat/test-bitbucket.R

Hi! I've added support for packages in Bitbucket repos (both public and private), I guess it closes #304. 
The code is the same except for some details (API calls, field names in the DESCRIPTION file, ...), so Github and Bitbucket chunks could be probably combined with some adjustments for each case. But I think it would be better to do it with a third case in mind (Gitlab?), so I've just left it separate for the moment.
About private authentication: when installling private Github packages with devtools, there is a `devtools::github_pat` function that retrieves the Personal Access Token stored in the envvar "GITHUB_PAT", but for the moment that's different with Bitbucket: there are no environment variables, and instead you set the user and password directly in the …

Added support for Bitbucket

---

R/restore-routines.R
tests/testthat/test-cache.R

Fixes #490.
Effectively, packrat attempts to detect corrupt cache entries (at least, for this particular case where the DESCRIPTION file is missing or empty); when discovered, it evicts that copy from the cache and a new one will later take its place after the package is rebuilt.
cc: @colearendt

detect and handle corrupt cache entries

---

DESCRIPTION
R/disable.R
R/packrat.R
R/snapshot.R
R/status.R
R/utils.R
inst/resources/init-rprofile.R
inst/resources/init.R
man/bundle.Rd
man/lockfile-metadata.Rd
man/packrat-external.Rd
man/packrat-mode.Rd
man/packrat-options.Rd
man/repository-management.Rd
man/restore.Rd

Now only checks for a lockfile, which is all that's really required during restore.
Closes #494.

relax 'packified' check during restore

---

tests/testthat/test-with_extlib.R

`packrat` packrat tests failed without this change.

fix packageVersion test; it may emit "smart" quotes

---

R/cache.R

With `packrat:::hash` and its `descLookup` argument, hashing is occasionally requested against DESCRIPTION files that are not within packages installed in an R library. `rsconnect` records description files as it creates a bundle; description information is also in the `manifest.json`.
Prior to this change, `packrat:::hash` produced different output if any field reordering occurred on the hashed description file.
DESCRIPTION file reordering initially feels unexpected, but is unavoidable when passing description data through an unordered construct, like a JSON object.
The field order used by `packrat:::hash` corresponds to common DESCRIPTION-file field order. This will help reduce the number of existing cached packages that see hash changes.

packrat:::hash has consistent output regardless of DESCRIPTION order

---

R/cache.R

Client `DESCRIPTION` files may contain a number of `Remote` fields describing how the package was acquired.
```
RemoteType: cran
RemoteRepos: structure("https://mirror.las.iastate.edu/CRAN", .Names = "CRAN")
RemoteSha: 1.66.0-1
RemotePkgType: source
```
These fields are not present when `packrat` restores a package from CRAN. This causes a hashing difference between the authoring environment and the restoring environment.
This change ignores `Remote*` fields for "cran" repositories when computing hashes.
Related: https://github.com/r-lib/remotes/blob/c509c3acf1ba7231c877352953f055227871e883/R/install-remote.R#L140

hashing ignores Remote* description fields when cran

---

DESCRIPTION
NEWS.md
R/dependencies.R
tests/testthat/resources/broken-chunks.Rmd
tests/testthat/test-dependencies.R

* Goal: Retrieve dependencies from each chunk independently.  
* Reason: `learnr` encourages users to provide broken code for students.  Currently since the complete tangled file can not be parsed, then no dependencies are found.
* Solution: 
* Tangle the file
* Split by a known comment value
* Parse the code chunks independently
* Combine dependencies
* Known workaround: source a separate, working R file that contains the library calls.  It seems odd to require this.
Related issue: https://github.com/rstudio/learnr/issues/209

make a fileDependencies.Rmd.tangle

---

DESCRIPTION
R/available-updates.R
R/downloader.R
R/gitlab.R
R/packrat.R
R/pkg.R
R/restore.R
R/snapshot.R
tests/testthat/test-bitbucket.R
tests/testthat/test-gitlab.R

Closes rstudio/packrat#559 by following pattern from rstudio/packrat#481. 
@kevinushey -- let me know if you have any suggestions/edits. I've tested locally and on deploy to RStudio Connect (after replacing tarball of `packrat` on Connect server) with following in RMarkdown:
```{r}
devtools::install_gitlab("alexkgold/riskgauge_pub")
riskgauge::add2(1, 1)
```

Add gitlab

---

R/paths.R

To resolve #557 - @kevinushey as discussed here is a very small pull request that sets the cache to be r version specific to avoid the internals problem of restoring with different r major versions. 
Any concerns let me know - happy to build on it to more fit the style if you like.
Adam

Added code for version specific cache

---

R/bitbucket.R
R/gitlab.R
R/install.R
R/restore.R
tests/testthat/test-with_extlib.R

cc: @aronatkins.
Most of the PR is just reformatting (adding `*Impl()` methods so they're easier to debug and step into) + some brown-bag fixes for warnings popping up with R 3.6.0. The meat of the PR is this:
```
pkgRecord$remote_host <- sub("api.bitbucket.org/2.0", "bitbucket.org", pkgRecord$remote_host, fixed = TRUE)
```

fix up API URLs when downloading from Bitbucket

---

R/restore.R
tests/testthat/projects/falsy-gitlab/deps.R
tests/testthat/projects/falsy-gitlab/packrat/packrat.lock
tests/testthat/test-packrat.R

ensure packages restored from GitLab / Bitbucket get RemoteType field

---

R/pkg.R
tests/testthat/resources/descriptions/falsy.packrat
tests/testthat/resources/descriptions/falsy.remotes
tests/testthat/test-packrat.R

This change makes a `packrat` annotated DESCRIPTION and a `remotes` annotated DESCRIPTION more compatible; strip the `remote_*` fields before comparing package records.

ignore remote fields when cleaning a github-sourced package record

---

R/pkg.R

Allow empty repository field

---

R/cache.R

See: https://github.com/r-lib/remotes/pull/310 and https://github.com/r-lib/remotes/issues/309

handle pak RemoteType standard as a package from a cran-like repository

---

R/pkg.R
tests/testthat/test-packrat.R

The commit https://github.com/rstudio/packrat/commit/e329cf15ddfaed7786d2b6831d749d87c66eec2c from https://github.com/rstudio/packrat/pull/569 created a function to help construct package records. Unfortunately, those new records included fields that are sometimes NULL and should be omitted from the package record when NULL. Reverted the constructor for now.
The commit https://github.com/rstudio/packrat/commit/29a4fdcb5d34113222b73e4eb2affd0e3fc3f1fd started using `identical` to compare the `RemoteType` field. This will not compare if the incoming data frame was read from DCF with strings-as-factors.
The test failures on `master` were caused by these commits. This PR also includes a couple extra checks that would have helped identify the problems.

optional fields are not in package record when NULL; avoid identical in RemoteType compares

---

_layouts/home.html

@kevinushey 
I’ve replaced your Google Analytics tracking number with the one for rstudio.com, which enables us to track users across domains.  Your site’s analytics will now be found under the rstudio.com property and I have built a segment for you to view your site’s metrics separate from other domains.  Data will populate from today forward and you will need to visit your previous property for historical data.  Thank you for merging this pull request so that we can get a full picture of online user behavior.

replaced GA tracking code to enable cross-domain tracking

---

R/pkg.R

an alternate tree-pruning approach from #614; part of an ongoing discussion with @andrie

avoid repeated package dependency processing

---

R/pkg.R
R/snapshot.R
R/utils.R

The option packrat.verbose.snapshot.dependencies prints additional detail about
the package dependency walk while constructing a project snapshot.
This is separate from the verbose option to .snapshotImpl, which is enabled
during normal packrat::snapshot use.
Note: This PR is layered on top of https://github.com/rstudio/packrat/pull/615 and replaces https://github.com/aronatkins/packrat/pull/1
Until https://github.com/rstudio/packrat/pull/615 is merged, those changes will show as differences, as well. You can see a more minimal diff at https://github.com/aronatkins/packrat/pull/2
CC @andrie
```R
options("packrat.verbose.snapshot.dependencies" = TRUE)
```
Sample output from a simple Shiny application; the trace indicates the walk depth, the current package, and if we are using prior …

verbose package dependency analysis

---

R/aaa-globals.R
R/utils.R

The utils.R definition of setNames was not visible to the package-build-time
calls to setNames in options.R because of R file-load order. As a result,
packrat would fall back to stats::setNames or err if stats was not loaded.

define setNames ahead of options.R

---

R/pkg.R
R/restore.R
inst/resources/init.R

It's possible for an R session to be configured with multiple repositories, each providing different versions of a particular package. In such a case, the rownames of `available.packages()` may no longer be the package name; they may instead be e.g. `digest.1` with tags appended to ensure uniqueness.
To avoid this issue, we should query the `"Package"` field of the `available.packages()` output directly.
(Note that normally there will only be a single entry for each package, but this behavior can be adjusted by modifying the filters passed to `available.packages()`)

don't use rownames when looking for CRAN packages

---

NEWS.md
R/dependencies.R
tests/testthat/resources/emoji.R
tests/testthat/test-dependencies.R

Function argument pairlists were not deeply walked previously.
fixes #630

additional expression recursion

---

NEWS.md
R/dependencies.R
tests/testthat/resources/unknown-engines.Rmd
tests/testthat/test-dependencies.R

Closes https://github.com/rstudio/packrat/issues/639.
This also resolves an issue where Packrat would execute non-R code chunks during the dependency discovery process (😱 ) by overriding any other engines during dependency discovery.

don't attempt to execute non-R engines; suppress knitr warnings for unknown engines

---

NEWS.md
R/bitbucket.R
R/downloader.R
R/github.R
R/gitlab.R
R/restore.R

We have started seeing errors when folks are using packrat to install private GitHub packages. This is rooted in the fact that `devtools` has removed the `github_pat` function in its 2.4.3 release.
* use authenticated downloaders when httr is installed and
authentication is available.
* err in github/gitlab/bitbucket downloaders, which provides
more information on failure to restore.
* remove github/gitlab/bitbucket download calls from downloadImpl,
as all downloadWithRetries calls are prefaced by repo-specific
download calls.
* err on all non-200 HTTP statuses for github/gitlab/bitbucket.
previously, whatever content we downloaded would be used,
which could be empty, or a JSON error document, or whatever.
R errors such as the lack of `devtools::github_pat` would now appear like:
``` …
```

stop using devtools::github_pat, as it is no longer available

---

NEWS.md
R/dependencies.R
R/library-support.R
R/recursive-package-dependencies.R
tests/testthat/test-dependencies.R

previously, we ignored only direct dependencies
Given a Shiny application having:
```r
library(shiny)
library(emo) # hadley/emo
ui <- fluidPage("So much", emo::ji("dancing"))
server <- function(input, output) {}
shinyApp(ui = ui, server = server)
```
The default set of dependencies:
```
> packrat:::appDependencies(".")
[1] "R6"          "Rcpp"        "assertthat"  "base64enc"   "bslib"       "cachem"      "commonmark" 
[8] "crayon"      "digest"      "ellipsis"    "emo"         "fastmap"     "fontawesome" "fs"         
[15] "generics"    "glue"        "htmltools"   "httpuv"      "jquerylib"   "jsonlite"    "later"      
[22] "lifecycle"   "lubridate"   "magrittr"    "mime"        "packrat"     "promises"    "purrr"      
[29] "rappdirs"    "rlang"       "sass"        "shiny" …
```

ignore packages when recursively enumerating dependencies

---

R/pkg.R

Gitlab is missing getting RemoteSubdir.
RStudio Connect is throwing error during deployment.
```
Error in (function() {: No DESCRIPTION file was found in the archive for packageName
```

Adds RemoteSubdir for gitlab.

---

.github/workflows/pkgdown.yaml

The update happens when a release is created, and can be triggered manually. This workflow is exactly the same as the one used in `rsconnect` (https://github.com/rstudio/rsconnect/pull/590)

Add GH Actions workflow to update GH Pages

---

NEWS.md
R/restore.R
packrat.Rproj

Fix archive downloads for Bitbucket and GitLab source archives when they're called in `getSourceForPkgRecord()`.
Fixes #671
At first, I just flipped the polarity of the conditional evaluating the `bitbucketDownload()` and `gitlabDownload()` functions' output. But then I saw that the GitHub download workflow had been updated, so I modified Bitbucket and GitLab's download flow to follow GitHub's.
Still thinking about this.

Fix Bitbucket and GitLab download calls in `getSourceForPkgRecord()`

---

inst/resources/renv.R
tests/testthat/test-shiny.R

This change to the embedded renv needs to be back-ported before we take the next update.

renv unscoped settings & test splitting

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
NEWS.md
R/bundle.R
R/cranlike-repositories.R
R/env.R
R/install.R
R/pkg.R
R/platform.R
R/restore.R
R/testthat-helpers.R
R/utils.R
tests/testthat/test-env.R

This PR incorporates #678, but goes further, so will supersede that PR.
Fixes #648 
Packrat has previously forced the use of R's internal tar implementation. This is buggy in a number of situations, including any repository with a slug > 16 characters.
Note: The code is ready for review, but QA notes are incomplete.
Influenced by the approach taken in `renv`, we now define a function `tar_binary()` to encapsulate slightly more complex logic:
- If `TAR` is set, respect that;
- If on Unix, look for `tar` on the `PATH`;
- If on Windows, look for the system `tar` and use that if it exists (see [`renv` implementation](https://github.com/rstudio/renv/blob/2bea5cef7cb6c57e43580cf0a182cbe59ef3536a/R/tar.R#L14-L21))
- Otherwise, return `"internal"` and maybe emit a warning about long filenames.
I …

Update how `tar` binaries are discovered

---

NEWS.md
R/install.R
tests/testthat/test-install.R

Mask certain environment variables from subprocesses launched by Packrat.
There are two ways an environment variable can be added to the list of environment variables to mask:
- A predefined list of variables is built-in. This can be disabled by setting the option `packrat.mask.git.service.envvars` to `FALSE`.
- Users can define a character vector of additional variable names to mask in the option `packrat.masked.envvars`.
These are compiled in a function called `envvar_mask()`, which returns a named character vector of NAs with the names of variables to mask. This is used in the `R()` function that launches R subprocesses.
Other changes:
- A change was made to `system_check()` to add the argument `return_output = FALSE`, which captures and returns the output of the command, rather than …

Add environment masking to Packrat

---

R/restore.R

Previously, an error message in `appendRemoteInfoToDescription` referenced a variable that was out of scope. This small change removes that reference.
The variable was used to add the package reference to the error message. However, this function is only ever called in contexts that already add the package name to the error message, so I didn't think it was necessary to pass in an extra object to obtain that name for the error message.
Fixes #691 
None needed.

Remove reference to unassigned variable from error message

---

NEWS.md
R/pkg.R
R/remote-info.R
R/restore.R
tests/testthat/_snaps/pkg.md
tests/testthat/resources/descriptions/github
tests/testthat/resources/descriptions/github_subdir
tests/testthat/resources/descriptions/gitlab
tests/testthat/resources/descriptions/gitlab_subdir
tests/testthat/test-pkg.R
tests/testthat/test-remote-info.R

Fix an issue where Packrat would fail to restore packages from subdirectories of repositories.
There were a few complex nested calls to `as.data.frame()`, `c()`, and `list()` spread across `getSourceForPkgRecord()` that I attempted to simplify in an earlier update. I simplified them incorrectly, causing `subdir` properties to be dropped.
Because we don't have end-to-end tests set up, and this transformation was part of a long function, no tests caught the issue. I moved the transformations into their own function and added unit tests.
Stepping back, this problem stems from the overall complexity of Packrat's workflows. This solution does not directly address the complexity. It adds a bit of indirection to make the outer-level workflow clearer, but it doesn't reduce the overall complexity …

Fix issue adjusting `DESCRIPTION` files for SCM-backed packages in subdirectories of remote repos

---

R/packrat.R

This ensures that the warning message doesn't print after the error if restore fails. Currently the connect log looks like this:
```
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE, : arguments imply differing number of rows: 1, 0
Unable to fully restore the R packages associated with this deployment.
Please review the preceding messages to determine which package
encountered installation difficulty and the cause of the failure.
Warning message:
In packrat::restore(overwrite.dirty = TRUE, prompt = FALSE, restart = FALSE) :
The most recent snapshot was generated using R version 4.2.1
```

Immediately warn about differing R version

---

NEWS.md
R/renv.R
R/restore.R
inst/vendor/renv.R

Loads binary packages at install time, which traps some environment compatibility problems. The package is removed from the packrat library and never reaches the packrat cache.
Fixes #712
The following Dockerfile examples show failures occurring at restore-time; the "runtime" script.R is never executed.
This first example shows how an install-time package load can identify missing system dependencies.
<details>
<summary>Dockerfile.packrat identifying missing (jags) system dependencies
```dockerfile
FROM rstudio/r-base:4.3-jammy AS base
RUN apt-get update && apt-get -y install pkg-config
ARG REPOSITORY=https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
RUN echo "options(repos = c(CRAN = '${REPOSITORY}'))" >> /opt/R/4.3.0/lib/R/etc/Rprofile.site
RUN R -s -e …
```

binary package validation (via renv)

---

.lintr
NEWS.md
R/renv.R
inst/vendor/renv.R

This PR updates `renv` to the latest dev version, https://github.com/rstudio/renv/commit/42c22c01d3bc02968b52d2049dcef17e49b5b29a. This includes the commit that should fix #716.

Update `renv` to latest dev version

---

R/renv.R
inst/vendor/renv.R

Turns out the changes between this and the prior pull (#718) request were only the version number.
Related to #716.

Bump `renv` version

---

R/renv.R
inst/vendor/renv.R

Bumped the vendored version of `renv` to the latest dev version. This version includes expansions and bugfixes in Linux distro detection for Posit Package Manager binary URL rewriting. The commit used is [here](https://github.com/rstudio/renv/commit/1f5bafc05a09ce6b30b83b835ffcd70547fe4fae).
This is the set of changes between the latest `renv` release and this dev commit: [Comparing changes](https://github.com/rstudio/renv/compare/e49d9be9528e0ff73b673f97382731c140013474...1f5bafc05a09ce6b30b83b835ffcd70547fe4fae). There are few functional changes other than these fixes.
This is the set of changes between the last vendored `renv` release and the new commit: [Comparing changes](https://github.com/rstudio/renv/compare/5dc2fc934867a1b34ec9d1c594dc57d3c9698650...1f5bafc05a09ce6b30b83b835ffcd70 …

Update vendored `renv` to include Linux distro detection bugfixes

---

NEWS.md
R/restore.R
tests/testthat/test-packrat.R
tests/testthat/test-restore.R

First, the `installPkg()` function no longer does additional work when the package was discovered in the cache. This avoids the most common situation where multiple processes performing package installation can race to the `annotatePkgDesc()` and `moveInstalledPackageToCache()` calls.
Second, `annotatePkgDesc()` writes its update to a temporary file before renaming to the target `DESCRIPTION`. This avoids a (now more rare) situation where a second process might see an incompletely written `DESCRIPTION` file.
As a side-effect, only the originally installing actor will annotate the `DESCRIPTION`. Previously, an update occurred even when the package was used from the cache, which overwrote an existing annotation.
Update: After thinking about this problem a bit more, realized that the root …

installPkg: do no work when using cached package and annotate safely

---

NEWS.md
R/pkg.R
packrat.Rproj

Look at biocViews before Repository when deciding if a package is from Bioconductor.
See https://github.com/rstudio/rsconnect/issues/1134

bioconductor: modern bioc DESCRIPTION files have Repository

---

NEWS.md
R/restore.R

rename downloaded files when they do not mirror convention

---

R/lockfile.R
R/packrat.R
tests/testthat/lockfiles/lockfile-norepos.txt
tests/testthat/test-lockfile.R
tests/testthat/test-packrat.R

Updates `readLockFile` so that it will succeed if repos are missing. The `repos` field gets set to `NULL`, and `restore()` will error when trying to restore packages with no repository set. Closes #741 
I air formatted the files I touched so the diff looks a little big, but the actual changes are in b38a363 and 6e30f12. 00b7411ce66914fee82906df238025611328fd7b is just formatting.

Handle empty repository field in lockfile
