R/utils.R
=> slightly cleaner dropNull

R/utils.R, tests/testthat/test-ignores.R
Do not create an ignore file if it does not already exist and we have no content.
Fixes #206.
=> Do not create an empty ignore file.

R/cache.R, tests/testthat/test-hash.R
Related:
https://github.com/rstudio/connect/pull/514 (see here for summary)
https://github.com/rstudio/rsconnect/pull/42
=> Allow hashes to be calculated based on non-installed DESCRIPTION files

R/dependencies.R
See https://github.com/rstudio/rmarkdown/pull/485
All tests pass
=> Allow YAML headers to end with dots

R/downloader.R
=> add "wininet" download method as default for non-secure with R>=3.2

R/dependencies.R, tests/testthat/resources/emoji.Rmd, tests/testthat/resources/evaluate-deps.Rmd, tests/testthat/test-dependencies.R
=> discover dependencies in inline chunks

DESCRIPTION, R/update.R, inst/resources/init-rprofile.R, inst/resources/init.R
=> avoid issues with command line quoting w/R 3.4.3 + Windows

DESCRIPTION, NEWS.md, R/packrat-mode.R, R/packrat.R, inst/resources/init-rprofile.R, inst/resources/init.R
Part of the associated fix for https://github.com/rstudio/rstudio/issues/3158.
=> initializing an existing project no longer re-snapshots, restores

NEWS.md, R/external.R, man/packrat-external.Rd, tests/testthat/test-with_extlib.R
- fixes #488, "with_extlib without the package"
- included testthat test
=> change with_extlib to work without packages

R/pkg.R
=> GitHub packages include RemoteRef in packrat.lock

custom-repos.md
Fixed a bug where it makes it impossible to run this script on a windows machine.
=> Updates documentation to work on Windows

R/install.R
=> decompress packages into private dir

_layouts/home.html
Updated GA tracking code to include both new RStudio websites and sites omitted in the April change.
@kevinushey  please review
=> updated GA tracking code to include new RStudio websites

NEWS.md
Noticed that we did not add NEWS for the recursion improvement. Here's one option for wording.
=> NEWS about dependency improvement

NEWS.md, R/dependencies.R, tests/testthat/resources/loading-packages.R, tests/testthat/test-dependencies.R
=> requireNamespace and loadNamespace do not accept symbols as package names

DESCRIPTION, NEWS.md, inst/resources/init-rprofile.R, inst/resources/init.R
=> CRAN release 0.7.0

NEWS.md, R/cache.R, tests/testthat/test-hash.R
=> cache RemoteType: url similarly to CRAN

NEWS.md, R/options.R, tests/testthat/test-options.R
=> option setting does not modify other options

.github/workflows/R-CMD-check.yaml
=> revisit GHA based on latest r-lib/actions guidance

NEWS.md, R/dependencies.R, tests/testthat/test-dependencies.R
=> build ignore expressions as expected by renv rather than rooted paths

.Rbuildignore, .github/workflows/lint.yaml, .lintr, R/aaa-globals.R, R/augment-rprofile.R, R/available-updates.R, R/bitbucket.R, R/bundle.R, R/dependencies.R, R/external.R, R/get-package-actions.R, R/gitlab.R, R/hooks.R, R/install.R, R/lockfile-metadata.R, R/lockfile.R, R/packrat.R, R/pkg.R, R/pretty-print.R, R/restore.R, R/rstudio-protocol.R, R/search-path.R, R/utils.R, tests/testthat/test-hash.R, tests/testthat/test-packrat.R, tests/testthat/test-shiny.R
runs lintr during CI.
most existing lintr warnings are suppressed rather than reacting to them.
=> initial lintr configuration

RELEASE.md
inspired by https://github.com/rstudio/packrat/issues/706
=> release checklist adjustment

NEWS.md
=> add news for distro improvements
